### ISSUE TITLE
Building for x86_64 on M1 Mac

### ISSUE THREAD

**Issue by DanielFNG** [coin-or-tools/ThirdParty-HSL#12]
Hello, I'm having trouble installing and interfacing with Metis on an M1 Mac. I run configure, pointing to Metis libraries which were installed with the x86 version of homebrew. I also tell it to configure for an x86 build:

`./configure --with-metis-cflags=-I/usr/local/homebrew/Cellar/metis/5.1.0/include --with-metis-lflags="-L/usr/local/homebrew/Cellar/metis/5.1.0/lib -lmetis" build=x86_64-apple-darwin`

The output suggests that the build configuration has been set up correctly:

```
checking build system type... x86_64-apple-darwin21.4.0
checking host system type... x86_64-apple-darwin21.4.0
```

However when running `make` it fails at the following:

`ld: warning: ignoring file /usr/local/homebrew/Cellar/metis/5.1.0/lib/libmetis.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64`

Which suggests it is still building for arm64 despite the specified build type to ./configure. Is there another way of going about this or is the configuration being ignored by make for some reason?

By the way, I would compile for arm64 all the way through, but another program I'm using is currently failing on the arm64 build, hence going down this route.

**Comment by svigerske** [comment]
I guess that it is the compiler that builds for ARM by default and setting the build-type is not sufficient to change that (also it should be `--build=...`).
Try augmenting the compiler flags by setting `ADD_CFLAGS`, `ADD_FCFLAGS`, and `ADD_FFLAGS` to tell it to build for x86_64.

**Comment by DanielFNG** [comment]
Thank you, you were correct. I was mistakenly using the version of gfortran installed with arm64 homebrew:
```
gfortran: warning: this compiler does not support X86 (arch flags ignored)
```
I installed gfortran with x86 homebrew, set the environment variables `FC` and `F77` to point to the x86 gfortran, at which point just doing `./configure` worked with no other option changes required.
