### ISSUE TITLE
Compiling and Installing Ipopt: error after running 'make'

### ISSUE THREAD

**Issue by JiaYuanChng** [coin-or-tools/ThirdParty-HSL#13]
Hello,

I have been struggling to understand the [ipopt webpage](https://coin-or.github.io/Ipopt/INSTALL.html). I am confused if I should have the ASL, BLAS, LAPACK, HSL git-cloned, configured, make, and make install each in their own respective directories. And then the same procedure for Ipopt.

So, I have been following the steps explained in this [documentation](https://projects.coin-or.org/Ipopt/export/1861/trunk/Ipopt/doc/documentation.pdf) for the installation of Ipopt on a Unix system (my university's HPC cluster account). I wish to use the different linear solvers from HSL to solve a rather large PDE optimization problem written in Pyomo.

Below are the steps I managed to get through glitch free until an error popped up from running 'make':
1. Download a tarball from [www.coin-or.org/download/source/Ipopt]: I downloaded the `Ipopt-3.12.13.tgz`
2. 
```
gunzip Ipopt-3.12.13.tgz
tar xvf Ipopt-3.12.13.tar
mv Ipopt-3.12.13.tar CoinIpopt 
cd CoinIpopt
```
4. In the `CoinIpopt` directory
``` 
cd ThirdParty/Blas
./get.Blas
cd ../Lapack
./get.Lapack
cd ../ASL
./get.ASL 
```
5. I downloaded a full HSL code, unzip and renamed it:
``` 
gunzip coinhsl-2021.05.05.tar.gz
tar xf coinhsl-2021.05.05.tar
mv coinhsl-2021.05.05.tar coinhsl
```
6. I then copied this `coinhsl` directory into the `CoinIpopt/ThirdParty/HSL` directory
7. In the `CoinIpopt/ThirdParty/Mumps` directory, I ran `./get.Mumps`
8. Create a directory to compile Ipopt, then configure
``` 
mkdir CoinIpopt/build
cd CoinIpopt/build
../configure 
```
9. The configuration was successful. The last output line reads `configure: Main configuration of Ipopt successful`.
10. In the same `CoinIpopt/build` directory, I ran `make`.
```
Making all in ThirdParty/ASL
make[1]: Entering directory `CoinIpopt/build/ThirdParty/ASL'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `CoinIpopt/build/ThirdParty/ASL'
Making all in ThirdParty/Metis
make[1]: Entering directory `CoinIpopt/build/ThirdParty/Metis'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `CoinIpopt/build/ThirdParty/Metis'
Making all in ThirdParty/Blas
make[1]: Entering directory `CoinIpopt/build/ThirdParty/Blas'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `CoinIpopt/build/ThirdParty/Blas'
Making all in ThirdParty/Lapack
make[1]: Entering directory `CoinIpopt/build/ThirdParty/Lapack'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `CoinIpopt/build/ThirdParty/Lapack'
Making all in ThirdParty/HSL
make[1]: Entering directory `CoinIpopt/build/ThirdParty/HSL'
make  all-am
make[2]: Entering directory `CoinIpopt/build/ThirdParty/HSL'
/bin/sh ./../../libtool --mode=compile mpif90  -O    -c -o deps90.lo `test -f 'coinhsl/common/deps90.f90' || echo 'CoinIpopt/ThirdParty/HSL/'`coinhsl/common/deps90.f90
libtool: compile: unable to infer tagged configuration
libtool: compile: specify a tag with `--tag'
make[2]: *** [deps90.lo] Error 1
make[2]: Leaving directory `CoinIpopt/build/ThirdParty/HSL'
make[1]: *** [all] Error 2
make[1]: Leaving directory `CoinIpopt/build/ThirdParty/HSL'
make: *** [all-recursive] Error 1
```
While I thought the configuration was a success I would not have any problem with the rest, I was quickly disabused of that notion.

I would like to ask for some help on this.

ps. I previously downloaded ipopt using `conda install` and have been using that in Pyomo.

Thank you.

**Comment by svigerske** [comment]
> I have been struggling to understand the [ipopt webpage](https://coin-or.github.io/Ipopt/INSTALL.html). I am confused if I should have the ASL, BLAS, LAPACK, HSL git-cloned, configured, make, and make install each in their own respective directories. And then the same procedure for Ipopt.

Yes, first install the dependencies of Ipopt. Then install Ipopt.
Blas and Lapack come with many package managers, you don't have to build it from scratch.
For ASL and HSL, you will need to build from source.
For HSL, it may be good to have Metis, too. Metis comes with many package managers.


> So, I have been following the steps explained in this [documentation](https://projects.coin-or.org/Ipopt/export/1861/trunk/Ipopt/doc/documentation.pdf) for the installation of Ipopt on a Unix system (my university's HPC cluster account). I wish to use the different linear solvers from HSL to solve a rather large PDE optimization problem written in Pyomo.
> 
> Below are the steps I managed to get through glitch free until an error popped up from running 'make':
> 
>     1. Download a tarball from [www.coin-or.org/download/source/Ipopt]: I downloaded the `Ipopt-3.12.13.tgz`

3.12.13 is several years old and the 3.12 branch is no longer maintained.
Try using a current release, also for ThirdParty-ASL and ThirdParty-HSL.
There was a larger upgrade on the buildsystem some years ago, which may have fixed the libtool issue that you get.

**Comment by JiaYuanChng** [comment]
Thank you for the very swift reply.

I managed to get Ipopt compiled and worked using the git clone methods. 

Just one last question about the parallel solvers MA86 and MA97: [the 2015 documentation](https://projects.coin-or.org/Ipopt/browser/stable/3.11/Ipopt/doc/documentation.pdf?format=raw) says 

> The HSL codes HSL MA86 and HSL MA97 can run in parallel if compiled with OpenMP support.
By default, this is not enabled by Ipopt’s configure so far. To enable OpenMP with GNU compilers,
it has been reported that the following configure flags should be used:
```
ADD_CFLAGS=-fopenmp ADD_FFLAGS=-fopenmp ADD_CXXFLAGS=-fopenmp
```

If I would like to solve a problem parallelly using Ipopt with either one of MA86 or 97, will I have to load `openmp` or `openmpi` modules and add the above flags after `./configure`?

**Comment by svigerske** [comment]
The 2015 docu is outdated. With current ThirdParty-HSL, OpenMP is enabled by default.

(Open)MPI is something different to OpenMP. None of the HSL codes, nor Ipopt, support this.

**Comment by yezhengli-Mr9** [comment]
There is no make or configure in `coinhsl-2023.05.26.tar.gz`
```bash
gunzip coinhsl-2023.05.26.tar.gz
tar xf coinhsl-2023.05.26.tar
mv coinhsl-2023.05.26.tar coinhsl
coinhsl-archive-2023.05.26.tar
coinhsl$ ls
ChangeLog  common  LICENCE  ma27  ma28  mc19  meson.build  meson_options.txt  README
```
