### ISSUE TITLE
HSL for IPOPT in Ubuntu

### ISSUE THREAD

**Issue by VartanAhrensKayayan** [coin-or-tools/ThirdParty-HSL#14]
I got the academic license for HSL and I am trying to get build into my computer in order to get Ipopt. I followed the steps (untar, rename, configure, make, make install) but then the Ipopt installation failed because there is no MA27. I check the ThirdParty-HSL log and there is in fact no MA27 (Checking for MA27, result: no). But inside the coinhsl folder I can see a folder labeled MA27 and I expect it to be there so I am wondering if I am missing something and what I can do to remediate the problem. Thank you.

**Comment by svigerske** [comment]
`configure` is looking for `coinhsl/ma27/ma27d.f` in the source dir of ThirdParty-HSL. Can you check again?

**Comment by VartanAhrensKayayan** [comment]
Ok, I apologize for taking your time.

I had:
computerName/coinhsl/ma27/ma27d.f
computerName/ThirdParty-HSL/

But then moving coinhsl into the latter worked:
computerName/ThirdParty-HSL/coinhsl

So the problem is solved. Would it be worthwhile to make that clear in the readme? I can take attempt it if so. Otherwise consider my issue closed and let the solution be here. I guess I could have --srcdir=DIR also but I could not figure that out.

**Comment by svigerske** [comment]
I see. I added something to the README.md in 302f75c. If you think it needs more, sure, you can propose some modifications.

`--srcdir` is for something else, I believe. That may not have done what you expect.
