### ISSUE TITLE
How to get HSL to find MA27?

### ISSUE THREAD

**Issue by makansij** [coin-or-tools/ThirdParty-HSL#15]
I’m trying to get the following simple combination working:  IPOPT, HSL, and MA27.  

I followed the instructions for each, and the link between IPOPT and HSL seems to be working, as indicated by the output of the `configure` script from the IPOPT source code:  

```checking for package HSL... yes``` 

However, the link between HSL and MA27 does NOT seem to be working, as indicated by the output from the `configure` script from the IPOPT source code: ` configure: error: Provided package HSL is not working or does not contain MA27.`, and also by the output from the HSL `configure` script in `ThirdParty-HSL`:   

``` checking for MA27... no``` 

I followed the steps here https://coin-or.github.io/Ipopt/INSTALL.html#EXTERNALCODE, and the steps for installing the dependencies in the links provided on that page: 

1) First, I went to https://www.hsl.rl.ac.uk/archive/index.html, and dowloaded the archive source code for MA27, after receiving the license of course. 

2.). I untarred the ` ma27-1.0.0.tar.gz` file, and moved all the contents to a directory called `coinhsl`, which I placed under `ThirdParty-HSL`, according to the directions under section *HSL* in the IPOPT installation instructions: https://coin-or.github.io/Ipopt/INSTALL.html#HSL. 

So, the directory looks as follows: 

- ThirdParty-HSL 
    - Coinhsl 
         - <files from ` ma27-1.0.0` > 

4.). Then, I navigated back to inside `ThirdParty-HSL`, and ran the `./configure` script in that directory. 

But this prints the output ` checking for MA27... no` as mentioned before.  As far as I can tell, I followed the directions exactly.  Are the directions here https://coin-or.github.io/Ipopt/INSTALL.html#EXTERNALCODE correct?  Or is there another way to get HSL to recognize the presence of MA27? 

The directions I linked to seem consistent with those posted on the page https://github.com/coin-or-tools/ThirdParty-HSL#installation-steps, so I’m wondering what’s missing.  The README file also seems consistent with this.   

Finally I tried using a shared library loading mechanism but to no avail.   

Related issues, which I browsed and didn’t find any new information:  

https://github.com/coin-or-tools/ThirdParty-HSL/issues/14 

https://github.com/coin-or-tools/ThirdParty-HSL/issues/11 

I’m on MacOS Monterey.

**Comment by svigerske** [comment]
The instructions in the Ipopt docu and at https://github.com/coin-or-tools/ThirdParty-HSL point to http://hsl.rl.ac.uk/ipopt/ for a reason. This is the HSL source archive that best fits to use with ThirdParty-HSL.

If you get only the MA27 archive, but want to use ThirdParty-HSL to build it, you will need to rearrange source files in a way that is similar to the coinhsl source code archive.
Or you build from the MA27 archive without the use of ThirdParty-HSL and point Ipopt to it via the `--with-hsl-lflags`/`--with-hsl-cflags` arguments (I haven't tried whether that works.)

**Comment by makansij** [comment]
Thanks for your response. Still not quite there yet.   

I downloaded the `coinhsl-archive-2021.05.05.tar.gz` from the link you cited.  I then proceeded as the instructions say: 

``` 

~/Downloads/ThirdParty-HSL$gunzip coinhsl-archive-2021.05.05.tar.gz  

~/Downloads/ThirdParty-HSL$tar xf coinhsl-archive-2021.05.05.tar  

~/Downloads/ThirdParty-HSL$ln -s coinhsl-archive-2021.05.05 coinhsl 

~/Downloads/ThirdParty-HSL$./configure 

``` 

However, I still see in the output of the `./configure` command, `checking for MA27... no`.  I assume there must be something wrong.  Is there a step that I’m not understanding?

**Comment by svigerske** [comment]
Did you build and install `ThirdParty-HSL` before configuring Ipopt?

**Comment by makansij** [comment]
When you say "_build and install `ThirdParty-HSL` before configuring Ipopt?_" I assume you are asking whether I've run `./configure`, as I showed above in the `ThirdParty-HSL` directory, before running `./configure` in the `Ipopt` directory?

I haven't even tried  running `./configure` in the `Ipopt` directory yet (I have run it previously in my lifetime, and the directory `Ipopt` still exists from me trying to debug this, but I haven't run it since opening this issue), because `checking for MA27... no` was enough to tell me that something is wrong already.  I assume after I get that working, then I can move forward with the Ipopt configure and install.  Or am I doing this in the wrong order?  

Are you suggesting that I need to remove previous any directories before running `./configure` in  the `ThirdParty-HSL` directory?

**Comment by svigerske** [comment]
Ah ok, I didn't get that this was the configure output from ThirdParty-HSL.

I don't know why it doesn't find MA27. It is just checking whether file `coinhsl/ma27/ma27d.f` is present.
As far as I see, this is included in coinhsl-archive-2021.05.05.tar.gz.

**Comment by makansij** [comment]
For me, the softlink was causing the issue.  I tried moving `coinhsl-archive-2021.05.05` to `coinhsl` instead of a softlink, and that got me the successful output `checking for MA27... yes`.

Perhaps we should investigate why this makes a difference?  And maybe update the instructions.

**Comment by svigerske** [comment]
I cannot reproduce with a symlink, also on macOS. So I couldn't investigate or explain why that didn't work for you.

**Comment by makansij** [comment]
Another theory:  The first time, I had the `ma27.x.y.z` archive in the `coinhsl` directory when I linked it to `coinhsl-archive-2021.05.05`.  It's possible that messed it up.  

After I ripped out the `coinhsl` directory and recreated it to contain *only* the files from `coinhsl-archive-2021.05.05` then it worked.  
That's my best guess, but I haven't tried to reproduce yet.

**Comment by makansij** [comment]
An additional note: In none of this documentation was it clear to me that “archive version” means the code available on the RHS panel of this page, https://www.hsl.rl.ac.uk/ipopt/.   That page ALSO contains an “Archive” link on the LHS, containing downloads available for each solver, including the MA27 one which I downloaded.  Unless @svigerske  had mentioned that to me, I would not have known that there was a difference.
