### ISSUE TITLE
Errors when linking to metis 5.1

### ISSUE THREAD

**Issue by wrcannon** [coin-or-tools/ThirdParty-HSL#20]
Hi,
I'm getting errors on a Mac M2 running Mac OS Ventura 13.5.2. I installed Metis 5.1.0 without any errors. But when I run I get the errors below:

% make
.
.
.
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       metis_adapter.lo
metis_adapter.c:207:17: warning: incompatible pointer types passing 'int *' to parameter of type 'idx_t *' (aka 'long long *') [-Wincompatible-pointer-types]
   METIS_NodeND(nvtxs, xadj, adjncy, (void*)0, options5, perm, iperm);
                ^~~~~
/usr/local/include/metis.h:210:36: note: passing argument to parameter 'nvtxs' here
METIS_API(int) METIS_NodeND(idx_t *nvtxs, idx_t *xadj, idx_t *adjncy, idx_t *vwgt,
                                   ^
metis_adapter.c:223:6: error: conflicting types for 'COINMETIS_NODEND'
void COINMETIS_NODEND(
     ^
metis_adapter.c:52:13: note: previous declaration is here
extern void COINMETIS_NODEND(int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *);
            ^
metis_adapter.c:235:6: error: conflicting types for 'coinmetis_nodend'
void coinmetis_nodend(
     ^
metis_adapter.c:53:13: note: previous declaration is here
extern void coinmetis_nodend(int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *);
            ^
metis_adapter.c:247:6: error: conflicting types for 'coinmetis_nodend_'
void coinmetis_nodend_(
     ^
metis_adapter.c:54:13: note: previous declaration is here
extern void coinmetis_nodend_(int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *);
            ^
metis_adapter.c:259:6: error: conflicting types for 'coinmetis_nodend__'
void coinmetis_nodend__(
     ^
metis_adapter.c:55:13: note: previous declaration is here
extern void coinmetis_nodend__(int *, idxtype *, idxtype *, int *, int *, idxtype *, idxtype *);
            ^
1 warning and 4 errors generated.
make[1]: *** [metis_adapter.lo] Error 1
make: *** [all] Error 2

**Comment by amontoison** [comment]
@wrcannon
Can you try the last release of [Coin-HSL](https://licences.stfc.ac.uk/product/coin-hsl) or [JuliaHSL](https://licences.stfc.ac.uk/product/julia-hsl) to see if you have the same issue?

**Comment by svigerske** [comment]
Maybe the type of argument `nvtxs` to `METIS_NodeND` changed from `int*` to `idx_t*` a while ago, but even with this fixed, a problem will likely be that your Metis installation expects 64bit integers (`IDXTYPEWIDTH` is 64 in `metis.h`?), while HSL expects 32bit, so things wouldn't run anyway.

Please make sure to have Metis installed with `IDXTYPEWIDTH` defined as 32. Then the difference `int*` vs `idx_t*` shouldn't matter, I hope.

**Comment by wrcannon** [comment]
That did it. Thanks for your help!
