### ISSUE TITLE
Link in README is broken

### ISSUE THREAD

**Issue by Fabian188** [coin-or-tools/ThirdParty-HSL#22]
In the README.md the link in

`Obtain a tarball with Coin-HSL source code from http://www.hsl.rl.ac.uk/ipopt/`

is broken. Correct would be 

```
Obtain a tarball with Coin-HSL source code from
https://licences.stfc.ac.uk/products/Software/HSL
with options Coin-HSL Archive or Coin-HSL
```

It would be interesting to add, if Coin-HSL Archive would be sufficient.

BTW, runs with Coin-HSL and gfortran 12.2 on Sonoma 14 on AppleSilicon.

**Comment by svigerske** [comment]
http://www.hsl.rl.ac.uk/ipopt/ is not broken to me. I get forwarded to https://licences.stfc.ac.uk/product/coin-hsl, which looks ok.
Though, we can of course also update the link.

Do you know what is part of Coin-HSL Archive (https://licences.stfc.ac.uk/product/coin-hsl-archive says only "limited selection")? Is that MA27 only? I suppose I can try to download it.

**Comment by svigerske** [comment]
In my coinhsl-archive-2021.05.05, there were MA27, MA28, and MC19 included. Building it with ThirdParty-HSL works for me and Ipopt could run with this lib.
