### ISSUE TITLE
undefined symbol: hsl_metis_ - When using dynamic library with shared loading

### ISSUE THREAD

**Issue by DanielChaseButterfield** [coin-or-tools/ThirdParty-HSL#24]
I'm trying to use HSL with [quad-sdk](https://github.com/robomechanics/quad-sdk), and I built HSL using this repository, and then made a dynamic link to make sure could find it:
```
ln -s /usr/local/lib/libcoinhsl.so /usr/local/lib/libhsl.so
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
```

However, when I try to run the [quad-sdk](https://github.com/robomechanics/quad-sdk), I get the following error:

```
[ WARN] [1715894497.088570991, 35.535000000]: NMPC solving fail
[robot_1/plan_publisher-5] killing on exit
Exception of type: DYNAMIC_LIBRARY_FAILURE in file "/home/lunarlab/Desktop/quadruped_sim_ws/src/quad-sdk/external/ipopt/coinbrew/Ipopt/src/Common/IpLibraryLoader.cpp" at line 86:
 Exception message: /usr/local/lib/libhsl.so: undefined symbol: hsl_metis_

EXIT: Library loading failure.
```

To me, this looks like a build error for HSL, where it couldn't find metis. However, when I run the configure script, it seems to properly detect metis:
```
checking for library Metis with combined link and compile check... yes
checking whether Metis library is linkable with Fortran compiler... yes
```

Similarly, I run `sudo make` and `sudo make install`, and don't see any explicit errors. What could be going wrong here?

Here is my metis version:
```
libmetis-dev is already the newest version (5.1.0.dfsg-5).
```

**Comment by svigerske** [comment]
I don't have any `hsl_metis` (or `hsl_metis_`) symbol or mention in my HSL.

But it seems that the HSL developers just published a new version 2 days ago, maybe they changed something that made the buildsystem here incompatible.

What version of the HSL source did you get?

**Comment by svigerske** [comment]
I cannot get the current version of HSL, at least not for free, as I'm neither employed nor a student at an academic institution, and there is no option for guests in these very extensive download forms.

If you can post a list of files in your coinhsl download, and have a look where hsl_metis is defined, we may be able to guess what changes needs to be done in ThirdParty-HSL.

**Comment by DanielChaseButterfield** [comment]
I download the version of CoinHSL 2024.05.15. Oh yeah, it's the new version.

**Comment by DanielChaseButterfield** [comment]
Oh man, I didn't realize that you wouldn't have access to the newest version. But unfortunately, I also cannot provide any files or code information due to my newly signed NDA. I'm not sure how to get around this... Maybe we just add a notification to this repository that it doesn't work with the newest version (2024.05.15)?

Regardless though, now that I know it's an issue with the most recent version, this isn't that big of a concern, as I was able to get it working with an older one. I could just close this issue for now.

**Comment by DanielChaseButterfield** [comment]
Maybe we just add a notification to this repository that it doesn't work with the newest version (2024.05.15)?

**Comment by svigerske** [comment]
Sorry, I was not asking for the files itself, but the list of filenames, and the name of the file where hsl_metis is defined. So I can start guessing what would need to be done to get this to work (and you try it out then). Maybe it is only a small change.

**Comment by svigerske** [comment]
@jfowkes Could you give some hint on what has changed in coinhsl 2024.05.15 that would break our buildsystem here?

**Comment by jfowkes** [comment]
> @jfowkes Could you give some hint on what has changed in coinhsl 2024.05.15 that would break our buildsystem here?

@AndrewLister-STFC what has changed in CoinHSL 2024.05.15 that has broken the ThirdParty-HSL build system?

**Comment by AndrewLister-STFC** [comment]
Sorry this broke the build! It actually uses the ideas from the metis adapter here that were added in a previous version. The difference in this version that causes this is a global replace (here's one example of the change):
```
<   103     CALL METIS_NODEND(N,KEEP(IPE),KEEP(IFCT),METFTN,METOPT,
---
>   103     CALL hsl_metis(N,KEEP(IPE),KEEP(IFCT),METFTN,METOPT,
```
our build script then no longer needs to build with
```
add_global_arguments(['-Dmetis_nodend=hsl_metis', '-DMETIS_NODEND=hsl_metis'], language : 'fortran')
```
