### ISSUE TITLE
Bump 2.2.5

### ISSUE THREAD

**Issue by giovanichaves** [coin-or-tools/ThirdParty-HSL#27]
@svigerske bumped version 2.2.5 but no release tag was created

**Comment by giovanichaves** [comment]
@tkralphs would you like to do the honours?

**Comment by svigerske** [comment]
I increased the version in configure.ac to the one that the next release is expected to have.

There was only one change added since 2.2.4, some workaround for macOS.

So you want a new release for this?

**Comment by giovanichaves** [comment]
Aha, no need to then in this case. We can hold until the next.
Just saw the bump but no tag and wondered if you forgot

**Comment by svigerske** [comment]
2.2.5 has been released.
