### ISSUE TITLE
not finding mc68

### ISSUE THREAD

**Issue by sylmio** [coin-or-tools/ThirdParty-HSL#3]
When doing ./configure, does not detect mc68, and Ipopt is not starting due to missing mc68_default_control.

To solve the problem, I edited the configure file and replaced $F90 by $FC for the mc68 block.

I guess it should be solve by changing configuration files for automake and autoconf, but could not use them.

**Comment by svigerske** [comment]
Thank you. That `$F90` must have been some leftover from a while ago. I don't really understand why I haven't had that problem.
