### ISSUE TITLE
fail to configure

### ISSUE THREAD

**Issue by TAOGZ** [coin-or-tools/ThirdParty-HSL#5]
Hi, I am using this package to configure the HSL.
when I run the configure, the system notices me that thie file does not have an app associated with it for performing this action......

**Comment by svigerske** [comment]
I have no idea what is meant by "thie file".

**Comment by TAOGZ** [comment]
> 
> 
> I have no idea what is meant by "thie file".

Sorry, it should be "this file"

**Comment by svigerske** [comment]
Hmm, which is the file it referes to? What kind of system is that? What is the output before and the exact error message?

**Comment by TAOGZ** [comment]
> 
> 
> Hmm, which is the file it referes to? What kind of system is that? What is the output before and the exact error message?

The file is "configure". I attempted to run this file on Windows.
The exact output message is "This file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Setting page."
This error occurs when I am following the instructions:
```
./configure
make
sudo make install
```
Thank you very much

**Comment by TAOGZ** [comment]
> 
> 
> Hmm, which is the file it referes to? What kind of system is that? What is the output before and the exact error message?

Thank you. I solved this problem.
I want to know if I must install Microsoft visual studio to make "./configure" successful?

**Comment by svigerske** [comment]
configure is a bash script, so you need bash. The preferred way is to have MSys2 with some additional tools available.

If you came to ThirdParty-HSL because you wanted to build Ipopt, then follow the Ipopt installation instructions, in particular https://coin-or.github.io/Ipopt/INSTALL.html#SYSTEMPACKAGES_MSYS.

Some of the instructions in https://coin-or.github.io/user_introduction also apply, though for ThirdParty-HSL you can ignore anything that instructs to get or call coinbrew.

You need MSVS only if you want to use the MS compiler.

**Comment by TAOGZ** [comment]
> 
> 
> configure is a bash script, so you need bash. The preferred way is to have MSys2 with some additional tools available.
> 
> If you came to ThirdParty-HSL because you wanted to build Ipopt, then follow the Ipopt installation instructions, in particular https://coin-or.github.io/Ipopt/INSTALL.html#SYSTEMPACKAGES_MSYS.
> 
> Some of the instructions in https://coin-or.github.io/user_introduction also apply, though for ThirdParty-HSL you can ignore anything that instructs to get or call coinbrew.
> 
> You need MSVS only if you want to use the MS compiler.

Thank you very much.
I will read the instructions in detail.
