### ISSUE TITLE
Configure error: Could not find dsyev in Lapack

### ISSUE THREAD

**Issue by lidingxu** [coin-or-tools/ThirdParty-HSL#6]
Hi,
 I obtained the HSL stable source code, and I also have the Intel MKL library installed in /opt/intel/mkl/lib/intel64 of my Ubuntu 20.04 system.  As there is already an [issue](https://github.com/coin-or/Cbc/issues/252) with linking CBC against MKL, I followed the successful configure commands, but failed to link the HSL library against the MKL libary. My configure commands follow as
> ./configure -C --enable-static --disable-shared --with-lapack="-L/opt/intel/mkl/lib/intel64 -Wl,--start-group,libmkl_core.a,libmkl_intel_lp64.a,libmkl_intel_thread.a,libmkl_lapack95_ilp64.a,--end-group -fopenmp -lm"

However, the function dsyev_, dssev, DSYEV, DSYEV_ are not found in these libraries,

> checking for function dsyev_ in -L/opt/intel/mkl/lib/intel64 -Wl,--start-group,libmkl_core.a,libmkl_intel_lp64.a,libmkl_intel_thread.a,libmkl_lapack95_ilp64.a,--end-group -fopenmp -lm ... no
checking for function dsyev in -L/opt/intel/mkl/lib/intel64 -Wl,--start-group,libmkl_core.a,libmkl_intel_lp64.a,libmkl_intel_thread.a,libmkl_lapack95_ilp64.a,--end-group -fopenmp -lm ... no
checking for function DSYEV_ in -L/opt/intel/mkl/lib/intel64 -Wl,--start-group,libmkl_core.a,libmkl_intel_lp64.a,libmkl_intel_thread.a,libmkl_lapack95_ilp64.a,--end-group -fopenmp -lm ... no
checking for function DSYEV in -L/opt/intel/mkl/lib/intel64 -Wl,--start-group,libmkl_core.a,libmkl_intel_lp64.a,libmkl_intel_thread.a,libmkl_lapack95_ilp64.a,--end-group -fopenmp -lm ... no
configure: error: Could not find dsyev in Lapack

But I tried follows, there is a dsyev function in the libmkl_lapack95_ilp64.a:
< xld@xld-GB-GZ1DTi7:/opt/intel/mkl/lib/intel64$ nm libmkl_lapack95_ilp64.a | grep dsyev
dsyev.o:
                 U dsyev_
0000000000000000 T dsyev_f95_
dsyevd.o:
                 U dsyevd_
0000000000000000 T dsyevd_f95_
dsyevr.o:
                 U dsyevr_
0000000000000000 T dsyevr_f95_
dsyevx.o:
                 U dsyevx_
0000000000000000 T dsyevx_f95_

**Comment by svigerske** [comment]
The config.log file should give more details on why these checks failed.

**Comment by lidingxu** [comment]
The config.log file is attached. 
[config.log](https://github.com/coin-or-tools/ThirdParty-HSL/files/5022769/config.log)

**Comment by tkralphs** [comment]
Looking at `config.log`, the link check failed with this error:
```
/usr/bin/ld: cannot find libmkl_core.a: No such file or directory
/usr/bin/ld: cannot find libmkl_intel_lp64.a: No such file or directory
/usr/bin/ld: cannot find libmkl_intel_thread: No such file or directory
/usr/bin/ld: cannot find libmkl_lapack95_ilp64.a: No such file or directory
```
If you search for where those lines occur in `config.log`, you can then try to compile the failed program yourself with the same command line to see if you can replicate the error. From the posted output, it certainly looks like those files should be found, but there must be a mistake somewhere.

**Comment by lidingxu** [comment]
I try the following configure such that the libmkl_lapack95_ilp64.a is correctly located 

> ./configure -C --with-lapack=-L/opt/intel/mkl/lib/intel64 -lmkl_lapack95_ilp64

and it should contain the  dsyev_ symbol
but, the reference 'dsyev_' is undefined 
>configure:12689: checking for function dsyev_ in -L/opt/intel/mkl/lib/intel64 -lmkl_lapack95_ilp64 
configure:12717: gcc -o conftest -O2 -DNDEBUG    conftest.c -L/opt/intel/mkl/lib/intel64 -lmkl_lapack95_ilp64  >&5
/usr/bin/ld: /tmp/cc7gNpgG.o: in function `main':
conftest.c:(.text.startup+0x7): undefined reference to `dsyev_'
collect2: error: ld returned 1 exit status
configure:12717: $? = 1

[config.log](https://github.com/coin-or-tools/ThirdParty-HSL/files/5024168/config.log)

**Comment by svigerske** [comment]
The libmkl_lapack95_ilp64.a I have doesn't have `dsyev_`.
```
$ nm -o libmkl_*a | grep -w "dsyev_"
libmkl_intel_ilp64.a:_dsyev.o:0000000000000000 T dsyev_
libmkl_intel_lp64.a:_dsyev_lp64.o:0000000000000000 T dsyev_
```
MKL has documentation: https://software.intel.com/content/www/us/en/develop/documentation/mkl-linux-developer-guide/top/linking-your-application-with-the-intel-math-kernel-library/linking-examples/linking-on-intel-64-architecture-systems.html
